title: Inhoe Koo
description: Quantum computing, artificial intelligence, and quantum simulation.
url: "https://inaekoo.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - DEPLOYMENT.md
